version: '3.8'

services:
  receipt-processor:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped